# Generated by Django 5.2.16 on 2026-07-16 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('DATASET_IMPORTED', 'Dataset imported'), ('REPORT_GENERATED', 'Report generated'), ('DASHBOARD_CREATED', 'Dashboard created')], max_length=32)),
                ('target_type', models.CharField(help_text="The kind of object the event is about, e.g. 'dataset'.", max_length=32)),
                ('target_id', models.UUIDField(blank=True, help_text="The object's id, so the feed can link to it if it still exists.", null=True)),
                ('target_label', models.CharField(help_text="The object's name captured at record time.", max_length=255)),
                ('actor', models.ForeignKey(blank=True, help_text='The member who caused the event; kept if the user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Activity event',
                'verbose_name_plural': 'Activity events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='activity_ac_organiz_8f4549_idx')],
            },
        ),
    ]
