from unittest.mock import patch

import pytest

from apps.reports.adapters import FakeAIProvider, GeminiAdapter


def test_fake_ai_provider():
    """Test that the FakeAIProvider returns the expected canned response."""
    provider = FakeAIProvider(canned_response="Mocked reply")
    result = provider.generate_text("Hello AI")
    assert result == "Mocked reply for: Hello AI"


def test_gemini_adapter_missing_key():
    """Test that GeminiAdapter raises ValueError when no API key is provided."""
    with pytest.raises(ValueError, match="GEMINI_API_KEY is not configured."):
        GeminiAdapter(api_key="")


@patch("google.genai.Client")
def test_gemini_adapter_initialization(mock_client_class):
    """Test that GeminiAdapter initializes correctly with a key."""
    adapter = GeminiAdapter(api_key="test-key", model_name="gemini-fake")

    mock_client_class.assert_called_once_with(api_key="test-key")
    assert adapter.client == mock_client_class.return_value


@patch("google.genai.Client")
def test_gemini_adapter_generate_text(mock_client_class):
    """Test that GeminiAdapter calls the model correctly."""
    mock_client_instance = mock_client_class.return_value
    mock_client_instance.models.generate_content.return_value.text = "Generated by mock"

    adapter = GeminiAdapter(api_key="test-key", model_name="gemini-fake")
    result = adapter.generate_text("Prompt test")

    mock_client_instance.models.generate_content.assert_called_once_with(
        model="gemini-fake", contents="Prompt test"
    )
    assert result == "Generated by mock"
