# Generated by Django 5.2.16 on 2026-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, help_text='Optional summary; the AI writes one when it generates the dashboard.'),
        ),
    ]
