# Generated by Django 5.2.16 on 2026-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dashboard_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Position in the dashboard's widget sequence; set by reorder."),
        ),
    ]
